---
title: "ID05"
author: "Grupo 05"
date: "16/01/2020"
output:
  pdf_document: default
  html_document: default
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

```{r read dados cancro}

dadoscancro<- read.csv(file = "data/CancerMortalityEU.csv")
names(dadoscancro)
```


```{r dados pop}
dadospopulacao <- read.csv( file = "data/PopulationEU.csv")
names(dadospopulacao)
```

```{r packages}
install.packages("data.table")
install.packages("rmarkdown")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("here")
install.packages(c("tidyr", "devtools"))
install.packages("plyr")
library(plyr)
library(data.table)
library(rmarkdown)
library(tidyr)
library(devtools)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(here)
```

```{r organizar dataframe da população}

novopop<-dadospopulacao[,-c(3,5)]

POP<-gather(novopop,"Year","pop",4:22)
POP$Year<-sub(".", "", POP$Year)  #Tirar o primeiro caracter (X) dos anos
POP <- na.omit(POP)
```


```{r all idades pop}

totoid<- aggregate(POP$pop, by=list(POP$Year, POP$Country, POP$Sex), FUN=sum)
#Dataframe das mortes relativas ao cancro por Ano, País e Sexo
setnames(totoid, old = c("Group.1","Group.2","Group.3","x"), new = c("Year", "Country", "Sex","pop"))


totoid<- totoid[-c(1063:1593),]


names(totoid)
names(POP)
totoid<- totoid[-c(1063:1593),]

ageGroup<-rep("All", times = 1062)
totoid<-cbind(totoid,ageGroup)

POP<- rbind(POP, totoid)
POP
```



```{r organizar dataframe dos cancros}

#Cancros
novocancro<-dadoscancro[,-c(2,4,6)]

CANCRO<-gather(novocancro,"Year","cancer",4:17)
Sex<- rep(c("Females", "Males"), times = c(63504,63504))
CANCRO<-cbind(CANCRO,Sex)

CANCRO$Year<-sub("Females", "", CANCRO$Year) #Tirar a palavra Females dos anos
CANCRO$Year<-sub("Males", "", CANCRO$Year) #Tirar a palavra Males dos anos
CANCRO$Year<-sub(".", "", CANCRO$Year) #Tirar o underscore dos anos


CANCRO <- na.omit(CANCRO) #NO ENVIRONMENT NAO APARECE AS OBSERVACOES CERTAS

CANCRO <- na.omit(CANCRO) 

CANCRO<- CANCRO[CANCRO$CancerSite=="Bladder",]


```

```{r all idades cancro}

mortes<- aggregate(CANCRO$cancer, by=list(CANCRO$Year, CANCRO$Country, CANCRO$Sex, CANCRO$CancerSite), FUN=sum)
#Dataframe das mortes relativas ao cancro por Ano, País e Sexo
setnames(mortes, old = c("Group.1","Group.2","Group.3","Group.4","x"), new = c("Year", "Country", "Sex","CancerSite","cancer"))

ageGroup<-rep("All", times = 374)
mortes<-cbind(mortes,ageGroup)

CANCRO<- rbind(CANCRO, mortes)
CANCRO

```

```{r criar a dataset}
total<-merge(POP,CANCRO, by=c("Country", "Sex", "Year", "ageGroup"))
#Junção do CANCRO e POP para termos as duas dataframes cruzadas
```

```{r mrate2}
mRate <- 100000*(total$cancer/total$pop)
mRate<-round(mRate,3)

TabelaFinal<- cbind(total,mRate)
TabelaFinal
```

```{r Análise exploratória}

Paises_mulheres_selecionados<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & TabelaFinal$Sex=="Females" & TabelaFinal$ageGroup=="All",]
View(Paises_mulheres_selecionados)
Paises_mulheres_selecionados<-Paises_mulheres_selecionados[,-c(2,3,4,6,8)]

#Analise exploratória População

summary_pop<-Paises_mulheres_selecionados%>%
group_by(Country)%>% 
summarise(Mean=mean(pop), Max=max(pop), Min=min(pop), Median=median(pop), Std=sd(pop))
View(summary_pop)

#Analise exploratória Nº de cancros

summary_cancro<-Paises_mulheres_selecionados%>%
group_by(Country)%>% 
summarise(Mean=mean(cancer), Max=max(cancer), Min=min(cancer), Median=median(cancer), Std=sd(cancer))
View(summary_cancro)

```


```{r questão 1}

Paises_mulheres<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & TabelaFinal$Sex=="Females" & TabelaFinal$ageGroup=="All",]
View(Paises_mulheres)

ggplot(Paises_mulheres, aes(x=Paises_mulheres$Year, y=Paises_mulheres$mRate, group=Paises_mulheres$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_mulheres$Country) +
  labs(title = "Ratio de mortes feminino nos países selecionados", x= "Ano", y= "Ratio de mortes", color = "Paises")



Paises_homens<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & TabelaFinal$Sex=="Males" & TabelaFinal$ageGroup=="All",]


ggplot(Paises_homens, aes(x=Paises_homens$Year, y=Paises_homens$mRate, group=Paises_homens$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_homens$Country) +
  labs(title = "Ratio de mortes masculino nos países selecionados", x= "Ano", y= "Ratio de mortes", color = "Paises")

```

```{r questão 1 UE}
Paisestodos_mulheres<-TabelaFinal[TabelaFinal$Sex=="Females" & TabelaFinal$ageGroup=="All",-8]
sPOPPaisestodos_mulheres<- aggregate(Paisestodos_mulheres$pop, by=list(Paisestodos_mulheres$Year), FUN=sum)

sCANCERPaisestodos_mulheres<- aggregate(Paisestodos_mulheres$cancer, by=list(Paisestodos_mulheres$Year), FUN=sum)

uniaoeuropeia<-cbind(sPOPPaisestodos_mulheres,sCANCERPaisestodos_mulheres)
uniaoeuropeia<-uniaoeuropeia[,-3]
setnames(uniaoeuropeia,old=c("Group.1","x","x.1"), new=c("Year","pop","cancer"))
mRate <- 100000*(uniaoeuropeia$cancer/uniaoeuropeia$pop)
mRate<-round(mRate,3)
uniaoeuropeiafinalmulheres<- cbind(uniaoeuropeia,mRate)
View(uniaoeuropeiafinal)
Country<-rep("European Union",7)
Sex<-rep("Females",7)
CancerSite<-rep("Bladder",7)
ageGroup<-rep("All",7)
uniaoeuropeiafinalmulheres<-cbind(Country,uniaoeuropeiafinalmulheres,Sex,CancerSite,ageGroup)
View(uniaoeuropeiafinalmulheres)
Paises_mulheres<-rbind(uniaoeuropeiafinalmulheres,Paises_mulheres)


Paisestodos_homens<-TabelaFinal[TabelaFinal$Sex=="Males" & TabelaFinal$ageGroup=="All",-8]
sPOPPaisestodos_homens<- aggregate(Paisestodos_homens$pop, by=list(Paisestodos_homens$Year), FUN=sum)

sCANCERPaisestodos_homens<- aggregate(Paisestodos_homens$cancer, by=list(Paisestodos_homens$Year), FUN=sum)

uniaoeuropeia<-cbind(sPOPPaisestodos_homens,sCANCERPaisestodos_homens)
uniaoeuropeia<-uniaoeuropeia[,-3]
setnames(uniaoeuropeia,old=c("Group.1","x","x.1"), new=c("Year","pop","cancer"))
mRate <- 100000*(uniaoeuropeia$cancer/uniaoeuropeia$pop)
mRate<-round(mRate,3)
uniaoeuropeiafinalhomens<- cbind(uniaoeuropeia,mRate)
View(uniaoeuropeiafinalhomens)

Country<-rep("European Union",7)
Sex<-rep("Males",7)
CancerSite<-rep("Bladder",7)
ageGroup<-rep("All",7)
uniaoeuropeiafinalhomens<-cbind(Country,uniaoeuropeiafinalhomens,Sex,CancerSite,ageGroup)
View(uniaoeuropeiafinalhomens)
Paises_homens<-rbind(uniaoeuropeiafinalhomens,Paises_homens)




ggplot(Paises_mulheres, aes(x=Paises_mulheres$Year, y=Paises_mulheres$mRate, group=Paises_mulheres$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_mulheres$Country)+
  labs(title = "Ratio de mortes feminino nos países selecionados e na UE", x= "Ano", y= "Ratio de mortes", color = "Paises")

ggplot(Paises_homens, aes(x=Paises_homens$Year, y=Paises_homens$mRate, group=Paises_homens$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_homens$Country)+
  labs(title = "Ratio de mortes masculino nos países selecionados e na UE", x= "Ano", y= "Ratio de mortes", color = "Paises")
 


```

```{r questao 2}

Paises<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal"),]

#Grafico para comparar o mrate entre mulheres por faixa etaria em 2016
PaisesFaixas<- Paises[!Paises$ageGroup %in% c("All"),]
PaisesFaixas<-PaisesFaixas[PaisesFaixas$Year %in% 2016,]
PaisesFaixasFem<- PaisesFaixas[PaisesFaixas$Sex %in% "Females",]
PaisesFaixasFem<-PaisesFaixasFem[!PaisesFaixasFem$ageGroup %in% c("1-4","5-9","10-14","15-19","20-24"),]

ggplot(PaisesFaixasFem, aes(fill=Country, y=mRate, x=ageGroup)) +
geom_bar(position="dodge", stat="identity")+
   ggtitle("Taxa de mortalidade no ano de 2016 por faixa etária no sexo feminino")+
    xlab("Faixas Etárias")+
    ylab("Taxa de Mortalidade")+
    coord_flip()

#Grafico para comparar o mrate entre homens por faixa etaria em 2016
PaisesFaixas<- Paises[!Paises$ageGroup %in% c("All"),]
PaisesFaixas<-PaisesFaixas[PaisesFaixas$Year %in% 2016,]
PaisesFaixasMale<- PaisesFaixas[PaisesFaixas$Sex %in% "Males",]
PaisesFaixasMale<-PaisesFaixasMale[!PaisesFaixasMale$ageGroup %in% c("1-4","5-9","10-14","15-19","20-24", "25-29"),]

ggplot(PaisesFaixasMale, aes(fill=Country, y=mRate, x=ageGroup)) +
geom_bar(position="dodge", stat="identity")+
  ggtitle("Taxa de mortalidade no ano de 2016 por faixa etária no sexo masculino")+
  xlab("Faixas Etárias")+
  ylab("Taxa de Mortalidade")+
  coord_flip()

```

```{r Questão 3}

#DATA FRAME COM AS PERCENTAGENS 

Paises<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal"),]

Paises_mulheres<- Paises[Paises$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & Paises$Sex == "Females" & Paises$ageGroup == "All",] 

Paises_homens<- Paises[Paises$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & Paises$Sex == "Males" & Paises$ageGroup == "All",]

Pop_ambos_sexos<- aggregate(Paises$pop, by=list(Paises$Year, Paises$ageGroup, Paises$Country), FUN=sum) #somar a população do sexo feminino e masculino por classe etária, ano e país

All_idades<-Pop_ambos_sexos[Pop_ambos_sexos$Group.2 == "All",] #selecionar apenas a classe etária com todas as idades
setnames(All_idades, old = c("Group.1","Group.2","Group.3","x"), new = c("Year", "ageGroup", "Country","pop"))

Percentagem_mulheres<-(Paises_mulheres$cancer/All_idades$pop)*100

Percentagem_homens<-(Paises_homens$cancer/All_idades$pop)*100

Tabela_Questao3<-cbind(All_idades,Percentagem_mulheres,Percentagem_homens)

#SEXO FEMININO

Perc_mulheres_2011<-Tabela_Questao3$Percentagem_mulheres[Tabela_Questao3$Year == 2011]

Sub_perc_mulheres_2012<-Tabela_Questao3$Percentagem_mulheres[Tabela_Questao3$Year == 2012]-Perc_mulheres_2011

Sub_perc_mulheres_2013<-Tabela_Questao3$Percentagem_mulheres[Tabela_Questao3$Year == 2013]-Perc_mulheres_2011

Sub_perc_mulheres_2014<-Tabela_Questao3$Percentagem_mulheres[Tabela_Questao3$Year == 2014]-Perc_mulheres_2011

Sub_perc_mulheres_2015<-Tabela_Questao3$Percentagem_mulheres[Tabela_Questao3$Year == 2015]-Perc_mulheres_2011

Sub_perc_mulheres_2016<-Tabela_Questao3$Percentagem_mulheres[Tabela_Questao3$Year == 2016]-Perc_mulheres_2011

Year<-rep(c("2011","2012","2013","2014","2015","2016"),each=5)
Country<-rep(c("Belgium", "Finland", "Italy", "Netherlands", "Portugal"),6)

Percentagens_mulheres<-c(Perc_mulheres_2011,Sub_perc_mulheres_2012,Sub_perc_mulheres_2013,Sub_perc_mulheres_2014, Sub_perc_mulheres_2015, Sub_perc_mulheres_2016)

Tabela_Questao3_final_mulheres<-data.frame(Year, Country, Percentagens_mulheres)

ggplot(Tabela_Questao3_final_mulheres, aes(x=Tabela_Questao3_final_mulheres$Year, y=Tabela_Questao3_final_mulheres$Percentagens_mulheres, group=Tabela_Questao3_final_mulheres$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Tabela_Questao3_final_mulheres$Country) +
  labs(title = "Percentagem de mortes no sexo feminino", x= "Ano", y= "Percentagem de mortes", color = "Países")

#SEXO MASCULINO

Perc_homens_2011<-Tabela_Questao3$Percentagem_homens[Tabela_Questao3$Year == 2011]

Sub_perc_homens_2012<-Tabela_Questao3$Percentagem_homens[Tabela_Questao3$Year == 2012]-Perc_homens_2011

Sub_perc_homens_2013<-Tabela_Questao3$Percentagem_homens[Tabela_Questao3$Year == 2013]-Perc_homens_2011

Sub_perc_homens_2014<-Tabela_Questao3$Percentagem_homens[Tabela_Questao3$Year == 2014]-Perc_homens_2011

Sub_perc_homens_2015<-Tabela_Questao3$Percentagem_homens[Tabela_Questao3$Year == 2015]-Perc_homens_2011

Sub_perc_homens_2016<-Tabela_Questao3$Percentagem_homens[Tabela_Questao3$Year == 2016]-Perc_homens_2011

Percentagens_homens<-c(Perc_homens_2011,Sub_perc_homens_2012,Sub_perc_homens_2013,Sub_perc_homens_2014, Sub_perc_homens_2015, Sub_perc_homens_2016)

Tabela_Questao3_final_homens<-data.frame(Year, Country, Percentagens_homens)

ggplot(data=Tabela_Questao3_final_homens, aes(x=Tabela_Questao3_final_homens$Year, y=Tabela_Questao3_final_homens$Percentagens_homens, group=Tabela_Questao3_final_homens$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Tabela_Questao3_final_homens$Country) +
  labs(title = "Percentagem de mortes no sexo masculino", x= "Ano", y= "Percentagem de mortes", color = "Países")

```



```{r questão4}
#What are the five (5) most common cancers in 2011? in 2017 for your countries?
tratamento_dataframe2<-dadoscancro[,-c(2,4,6)]

TodosCancros<-gather(novocancro,"Year","cancer",4:17)
Sex<- rep(c("Females", "Males"), times = c(63504,63504))
TodosCancros<-cbind(TodosCancros,Sex)

TodosCancros$Year<-sub("Females", "", TodosCancros$Year) #Tirar a palavra Females dos anos
TodosCancros$Year<-sub("Males", "", TodosCancros$Year) #Tirar a palavra Males dos anos
TodosCancros$Year<-sub(".", "", TodosCancros$Year) #Tirar o underscore dos anos

TodosCancros <- na.omit(TodosCancros) #NO ENVIRONMENT NAO APARECE AS OBSERVACOES CERTAS

add_all<- aggregate(TodosCancros$cancer, by=list(TodosCancros$Year, TodosCancros$Country, TodosCancros$Sex, TodosCancros$CancerSite), FUN=sum)
#Dataframe das mortes relativas ao cancro por Ano, País e Sexo
setnames(add_all, old = c("Group.1","Group.2","Group.3","Group.4","x"), new = c("Year", "Country", "Sex","CancerSite","cancer"))

ageGroup<-rep("All", times = 5952)
add_all<-cbind(add_all,ageGroup)

TodosCancros<- rbind(TodosCancros, add_all)


total<-merge(POP,TodosCancros, by=c("Country", "Sex", "Year", "ageGroup"))
mRate <- 100000*(total$cancer/total$pop)
mRate<-round(mRate,3)

TabelaFinal2<- cbind(total,mRate)

Paises<- TabelaFinal2[TabelaFinal2$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal"),]


#Cancros mais comuns em 2011
Paises_2011<-Paises[Paises$Year %in% 2011,]
Paises_2011<-Paises_2011[Paises_2011$ageGroup %in% "All",]
Paises_2011<-Paises_2011[!Paises_2011$CancerSite %in% "All Cancers",]


levels(Paises_2011$CancerSite) <- list(CRJRAAC="Colon, Rectosigmoid Junction, Rectum, Anus and Anal Canal", BCNS="Brain and Central Nervous System", Larynx="Larynx", Ovary="Ovary", Oesophagus="Oesophagus", LIBD="Liver and Intrahepatic Bile Ducts", LOCP="Lip, Oral Cavity, Pharynx", Breast="Breast", Bladder="Bladder", KERP="Kidney, Except Renal Pelvis", Pancreas="Pancreas", ThyroidGland="Thyroid Gland", OPFU="Other Parts of Uterus", TBL="Trachea, Bronchus and Lung",Stomach= "Stomach", CervixUteri="Cervix Uteri", Prostate="Prostate", ALL="ALL" )

ggplot(Paises_2011, aes(fill=Sex, y=Paises_2011$mRate, x=Paises_2011$CancerSite)) +
geom_bar(position="dodge", stat="identity")+
   labs(title = "Cancros mais comuns em 2011", x= "Tipos de cancro por sexo", y= "Taxa de mortalidade", fill = "Sexo")+
    geom_text(aes(label = Paises_2011$mRate, y = Paises_2011$mRate + 0.05),
    position = position_dodge(0.9),vjust = 0, size = 2)+
    facet_grid(Paises_2011$Country)



#Cancros mais comuns em 2016
Paises<- TabelaFinal2[TabelaFinal2$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal"),]
Paises_2016<-Paises[Paises$Year %in% 2016,]
Paises_2016<-Paises_2016[Paises_2016$ageGroup %in% "All",]
Paises_2016<-Paises_2016[!Paises_2016$CancerSite %in% "All Cancers",]

levels(Paises_2016$CancerSite) <- list(CRJRAAC="Colon, Rectosigmoid Junction, Rectum, Anus and Anal Canal", BCNS="Brain and Central Nervous System", Larynx="Larynx", Ovary="Ovary", Oesophagus="Oesophagus", LIBD="Liver and Intrahepatic Bile Ducts", LOCP="Lip, Oral Cavity, Pharynx", Breast="Breast", Bladder="Bladder", KERP="Kidney, Except Renal Pelvis", Pancreas="Pancreas", ThyroidGland="Thyroid Gland", OPFU="Other Parts of Uterus", TBL="Trachea, Bronchus and Lung",Stomach= "Stomach", CervixUteri="Cervix Uteri", Prostate="Prostate", ALL="ALL" )

ggplot(Paises_2016, aes(fill=Sex, y=Paises_2016$mRate, x=Paises_2016$CancerSite)) +
geom_bar(position="dodge", stat="identity")+
   labs(title = "Cancros mais comuns em 2016", x= "Tipos de cancro por sexo", y= "Taxa de mortalidade", fill = "Sexo")+
    geom_text(aes(label = Paises_2016$mRate, y = Paises_2016$mRate + 0.05),
    position = position_dodge(0.9),vjust = 0, size = 2)+
    facet_grid(Paises_2016$Country)
```


